var Fragment = wp.element.Fragment;
var registerBlockType = wp.blocks.registerBlockType;
var _wp$editor = wp.editor,
    InnerBlocks = _wp$editor.InnerBlocks,
    BlockControls = _wp$editor.BlockControls,
    AlignmentToolbar = _wp$editor.AlignmentToolbar,
    BlockAlignmentToolbar = _wp$editor.BlockAlignmentToolbar,
    BlockVerticalAlignmentToolbar = _wp$editor.BlockVerticalAlignmentToolbar,
    PanelColorSettings = _wp$editor.PanelColorSettings,
    InspectorControls = _wp$editor.InspectorControls,
    RichText = _wp$editor.RichText,
    RichTextToolbarButton = _wp$editor.RichTextToolbarButton,
    RichTextShortcut = _wp$editor.RichTextShortcut;
var _wp$components = wp.components,
    PanelBody = _wp$components.PanelBody,
    TreeSelect = _wp$components.TreeSelect,
    TextareaControl = _wp$components.TextareaControl,
    TextControl = _wp$components.TextControl,
    ServerSideRender = _wp$components.ServerSideRender,
    ToggleControl = _wp$components.ToggleControl,
    SelectControl = _wp$components.SelectControl,
    CheckboxControl = _wp$components.CheckboxControl,
    RangeControl = _wp$components.RangeControl,
    Button = _wp$components.Button,
    Toolbar = _wp$components.Toolbar,
    FormFileUpload = _wp$components.FormFileUpload;
var _wp$richText = wp.richText,
    registerFormatType = _wp$richText.registerFormatType,
    toggleFormat = _wp$richText.toggleFormat;
var __ = wp.i18n.__;

var el = wp.element.createElement;
